# FIMG2D
BOARD_USES_SKIA_FIMGAPI := true

# (G)SCALER
BOARD_USES_SCALER := true
BOARD_USES_DT := true

# HDMI
BOARD_HDMI_INCAPABLE := true
BOARD_USES_GSC_VIDEO := true

# HWCServices
BOARD_USES_HWC_SERVICES := true

# Samsung LSI OpenMAX
#COMMON_GLOBAL_CFLAGS += -DUSE_NATIVE_SEC_NV12TILED

# OpenMAX video
BOARD_USE_DMA_BUF := true
BOARD_USE_METADATABUFFERTYPE := true
